In [1]:
import numpy as np
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18181818,
         8.78787879,   9.39393939,  10.        ,  10.60606061,
        11.21212121,  11.81818182,  12.42424242,  13.03030303,
        13.63636364,  14.24242424,  14.84848485,  15.45454545,
        16.06060606,  16.66666667,  17.27272727,  17.87878788,
        18.48484848,  19.09090909,  19.6969697 ,  20.3030303 ,
        20.90909091,  21.51515152,  22.12121212,  22.72727273,
        23.33333333,  23.93939394,  24.54545455,  25.15151515,
        25.75757576,  26.36363636,  26.96969697,  27.57575758,
        28.18181818,  28.78787879,  29.39393939,  30.        ])

In [2]:
#size可以放整數或tuple of ints
#low包含，high不包含，可以先放size再放high
content = np.random.randint(50,high=101,size=(50,5))

In [3]:
import pandas as pd
#給index及columns
df1 = pd.DataFrame(data = content,
             index=range(1,51),
             columns=['國文','英文','數學','地理','歷史'])

In [4]:
#print(df1)
(df1['國文']+df1['英文']+df1['數學']+df1['地理']+df1['歷史'])/5

1     71.8
2     80.6
3     74.0
4     77.2
5     74.2
6     69.4
7     76.2
8     68.6
9     69.4
10    84.8
11    67.6
12    80.2
13    80.0
14    74.8
15    84.0
16    72.0
17    80.8
18    69.0
19    72.8
20    71.2
21    78.2
22    74.2
23    74.8
24    74.6
25    70.8
26    82.2
27    75.4
28    75.2
29    69.0
30    79.4
31    77.8
32    82.6
33    82.2
34    87.4
35    75.8
36    73.8
37    74.2
38    72.0
39    81.2
40    82.4
41    63.4
42    69.2
43    64.4
44    80.2
45    68.4
46    73.4
47    70.0
48    66.0
49    72.8
50    76.4
dtype: float64

In [5]:
import pandas as pd
#給index及columns
df1 = pd.DataFrame(data = content,
             index=[f"第{i}號" for i in range(1,51)],
             columns=['國文','英文','數學','地理','歷史'])
df1

      國文  英文   數學   地理   歷史
第1號   58  96   71   71   63
第2號   96  84   65   58  100
第3號   81  61   61   78   89
第4號   95  52   77  100   62
第5號   85  97   53   69   67
第6號   50  96   54   58   89
第7號   82  69   85   60   85
第8號   91  50   57   79   66
第9號   63  50   81   91   62
第10號  67  76  100   97   84
第11號  98  51   64   68   57
第12號  84  70   57  100   90
第13號  56  98   99   58   89
第14號  73  65   61   95   80
第15號  97  96   55   92   80
第16號  67  61  100   73   59
第17號  56  99   98   52   99
第18號  51  63   53   88   90
第19號  74  56   86   66   82
第20號  57  64   89   92   54
第21號  81  98   55   87   70
第22號  96  72   54   66   83
第23號  73  86   80   58   77
第24號  60  57   99   57  100
第25號  71  62   71   62   88
第26號  80  56   83   96   96
第27號  85  65   99   65   63
第28號  52  90   80   56   98
第29號  61  53   51   92   88
第30號  92  92   91   58   64
第31號  77  76   89   96   51
第32號  92  78   76   75   92
第33號  94  98   87   82   50
第34號  97  92   99   69   80
第35號  60  95   75   64   85
第36號  66  61   62   93   87
第37號  94  81   77   56   63
第38號  50  82   55  100   73
第39號  62  66   86   94   98
第40號  86  67   71   91   97
第41號  57  79   62   65   54
第42號  68  83   59   85   51
第43號  61  58   50   76   77
第44號  92  95   68   73   73
第45號  63  52   92   85   50
第46號  78  50   78   74   87
第47號  53  89   98   54   56
第48號  64  59   52   62   93
第49號  68  51   76   90   79
第50號  88  59   84   73   78

In [6]:
df1.loc["第1號",:]

國文    58
英文    96
數學    71
地理    71
歷史    63
Name: 第1號, dtype: int64

In [7]:
df1.loc["第1號"]

國文    58
英文    96
數學    71
地理    71
歷史    63
Name: 第1號, dtype: int64

In [8]:
df1.loc[["第1號","第5號","第10號"]]

      國文  英文   數學  地理  歷史
第1號   58  96   71  71  63
第5號   85  97   53  69  67
第10號  67  76  100  97  84

In [9]:
df1.iloc[:5]

     國文  英文  數學   地理   歷史
第1號  58  96  71   71   63
第2號  96  84  65   58  100
第3號  81  61  61   78   89
第4號  95  52  77  100   62
第5號  85  97  53   69   67

In [10]:
df1.iloc[-6:]

      國文  英文  數學  地理  歷史
第45號  63  52  92  85  50
第46號  78  50  78  74  87
第47號  53  89  98  54  56
第48號  64  59  52  62  93
第49號  68  51  76  90  79
第50號  88  59  84  73  78

In [11]:
df1.loc['第17號':'第23號']

      國文  英文  數學  地理  歷史
第17號  56  99  98  52  99
第18號  51  63  53  88  90
第19號  74  56  86  66  82
第20號  57  64  89  92  54
第21號  81  98  55  87  70
第22號  96  72  54  66  83
第23號  73  86  80  58  77

In [12]:
df1.loc['第17號':'第23號','英文':]

      英文  數學  地理  歷史
第17號  99  98  52  99
第18號  63  53  88  90
第19號  56  86  66  82
第20號  64  89  92  54
第21號  98  55  87  70
第22號  72  54  66  83
第23號  86  80  58  77

In [13]:
#axis = 0 表直，axis = 1表橫
student_sum = df1.sum(axis = 1)
student_mean = df1.mean(axis = 1)

In [14]:
df1['總分'] = student_sum
df1['平均'] = student_mean
df1

      國文  英文   數學   地理   歷史   總分    平均
第1號   58  96   71   71   63  359  71.8
第2號   96  84   65   58  100  403  80.6
第3號   81  61   61   78   89  370  74.0
第4號   95  52   77  100   62  386  77.2
第5號   85  97   53   69   67  371  74.2
第6號   50  96   54   58   89  347  69.4
第7號   82  69   85   60   85  381  76.2
第8號   91  50   57   79   66  343  68.6
第9號   63  50   81   91   62  347  69.4
第10號  67  76  100   97   84  424  84.8
第11號  98  51   64   68   57  338  67.6
第12號  84  70   57  100   90  401  80.2
第13號  56  98   99   58   89  400  80.0
第14號  73  65   61   95   80  374  74.8
第15號  97  96   55   92   80  420  84.0
第16號  67  61  100   73   59  360  72.0
第17號  56  99   98   52   99  404  80.8
第18號  51  63   53   88   90  345  69.0
第19號  74  56   86   66   82  364  72.8
第20號  57  64   89   92   54  356  71.2
第21號  81  98   55   87   70  391  78.2
第22號  96  72   54   66   83  371  74.2
第23號  73  86   80   58   77  374  74.8
第24號  60  57   99   57  100  373  74.6
第25號  71  62   71   62   88  354  70.8
第26號  80  56   83   96   96  411  82.2
第27號  85  65   99   65   63  377  75.4
第28號  52  90   80   56   98  376  75.2
第29號  61  53   51   92   88  345  69.0
第30號  92  92   91   58   64  397  79.4
第31號  77  76   89   96   51  389  77.8
第32號  92  78   76   75   92  413  82.6
第33號  94  98   87   82   50  411  82.2
第34號  97  92   99   69   80  437  87.4
第35號  60  95   75   64   85  379  75.8
第36號  66  61   62   93   87  369  73.8
第37號  94  81   77   56   63  371  74.2
第38號  50  82   55  100   73  360  72.0
第39號  62  66   86   94   98  406  81.2
第40號  86  67   71   91   97  412  82.4
第41號  57  79   62   65   54  317  63.4
第42號  68  83   59   85   51  346  69.2
第43號  61  58   50   76   77  322  64.4
第44號  92  95   68   73   73  401  80.2
第45號  63  52   92   85   50  342  68.4
第46號  78  50   78   74   87  367  73.4
第47號  53  89   98   54   56  350  70.0
第48號  64  59   52   62   93  330  66.0
第49號  68  51   76   90   79  364  72.8
第50號  88  59   84   73   78  382  76.4

In [15]:
df2 = df1.sort_values(by = '平均',ascending = False)
df2[:6]

      國文  英文   數學  地理  歷史   總分    平均
第34號  97  92   99  69  80  437  87.4
第10號  67  76  100  97  84  424  84.8
第15號  97  96   55  92  80  420  84.0
第32號  92  78   76  75  92  413  82.6
第40號  86  67   71  91  97  412  82.4
第26號  80  56   83  96  96  411  82.2

In [16]:
df2[-5:]

      國文  英文  數學  地理  歷史   總分    平均
第45號  63  52  92  85  50  342  68.4
第11號  98  51  64  68  57  338  67.6
第48號  64  59  52  62  93  330  66.0
第43號  61  58  50  76  77  322  64.4
第41號  57  79  62  65  54  317  63.4

In [17]:
df2['排名'] = df1['總分'].rank(method='first',ascending = False)

In [18]:
df2

      國文  英文   數學   地理   歷史   總分    平均    排名
第34號  97  92   99   69   80  437  87.4   1.0
第10號  67  76  100   97   84  424  84.8   2.0
第15號  97  96   55   92   80  420  84.0   3.0
第32號  92  78   76   75   92  413  82.6   4.0
第40號  86  67   71   91   97  412  82.4   5.0
第26號  80  56   83   96   96  411  82.2   6.0
第33號  94  98   87   82   50  411  82.2   7.0
第39號  62  66   86   94   98  406  81.2   8.0
第17號  56  99   98   52   99  404  80.8   9.0
第2號   96  84   65   58  100  403  80.6  10.0
第12號  84  70   57  100   90  401  80.2  11.0
第44號  92  95   68   73   73  401  80.2  12.0
第13號  56  98   99   58   89  400  80.0  13.0
第30號  92  92   91   58   64  397  79.4  14.0
第21號  81  98   55   87   70  391  78.2  15.0
第31號  77  76   89   96   51  389  77.8  16.0
第4號   95  52   77  100   62  386  77.2  17.0
第50號  88  59   84   73   78  382  76.4  18.0
第7號   82  69   85   60   85  381  76.2  19.0
第35號  60  95   75   64   85  379  75.8  20.0
第27號  85  65   99   65   63  377  75.4  21.0
第28號  52  90   80   56   98  376  75.2  22.0
第23號  73  86   80   58   77  374  74.8  24.0
第14號  73  65   61   95   80  374  74.8  23.0
第24號  60  57   99   57  100  373  74.6  25.0
第22號  96  72   54   66   83  371  74.2  27.0
第5號   85  97   53   69   67  371  74.2  26.0
第37號  94  81   77   56   63  371  74.2  28.0
第3號   81  61   61   78   89  370  74.0  29.0
第36號  66  61   62   93   87  369  73.8  30.0
第46號  78  50   78   74   87  367  73.4  31.0
第49號  68  51   76   90   79  364  72.8  33.0
第19號  74  56   86   66   82  364  72.8  32.0
第16號  67  61  100   73   59  360  72.0  34.0
第38號  50  82   55  100   73  360  72.0  35.0
第1號   58  96   71   71   63  359  71.8  36.0
第20號  57  64   89   92   54  356  71.2  37.0
第25號  71  62   71   62   88  354  70.8  38.0
第47號  53  89   98   54   56  350  70.0  39.0
第6號   50  96   54   58   89  347  69.4  40.0
第9號   63  50   81   91   62  347  69.4  41.0
第42號  68  83   59   85   51  346  69.2  42.0
第18號  51  63   53   88   90  345  69.0  43.0
第29號  61  53   51   92   88  345  69.0  44.0
第8號   91  50   57   79   66  343  68.6  45.0
第45號  63  52   92   85   50  342  68.4  46.0
第11號  98  51   64   68   57  338  67.6  47.0
第48號  64  59   52   62   93  330  66.0  48.0
第43號  61  58   50   76   77  322  64.4  49.0
第41號  57  79   62   65   54  317  63.4  50.0